# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bcea6ce23f446fea89a72a52ff32b5ca7facb7d13c97a426670eca94b169eb955c333ced232ce2a1d70e9931305f6bf0e760f724943b8e2c0994a45fb7d4ad0

test:
  secret_key_base: eabfc1bf6eb54df147fda12fedbbd63b6621141007eeec818a65e9f573a615dc6c00bd202cf6cd53f7ed30d92cc2d22eed4903f826819ad276decc8404e441ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
